# Generated by Django 3.2.4 on 2021-11-01 06:25

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211027_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Discord ID must be in the format string#1234', regex='^.{3,32}#[0-9]{4}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
