# Generated by Django 3.2.4 on 2021-11-01 06:30

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211101_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Discord ID must be in the format string#1234', regex='^.{3,32}#[0-9]{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
