# Generated by Django 3.2.4 on 2021-11-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproducts',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='userproducts',
            name='username',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='UserProducts',
        ),
    ]
