# Generated by Django 3.2.4 on 2021-11-12 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('current_stock', models.BooleanField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_updated', models.TimeField()),
                ('product_id', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_interval', models.CharField(max_length=200)),
                ('notification_method', models.CharField(max_length=200)),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
