# Generated by Django 3.2.4 on 2021-11-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
