# Generated by Django 3.2.4 on 2021-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211114_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='notification_interval',
            field=models.CharField(choices=[('Fast', 'Notifications every 1 min'), ('Medium', 'Notifications every 10 min'), ('Slow', 'Notifications every 1 hour')], default='Medium', max_length=200),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='notification_method',
            field=models.CharField(choices=[('Email', 'Notications by Email'), ('Discord', 'Notifications by Discord DM'), ('SMS', 'Notifications by Text Message')], default='Email', max_length=200),
        ),
    ]
